format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-03-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.cice.r.1958-03-01-00000.nc
  hashes:
    binhash: fbac8a066ec08bda619c2c63acd599d1
    md5: a07022a336a1a6d4fc482bbbeaee34b8
work/access-om3.cpl.r.1958-03-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.cpl.r.1958-03-01-00000.nc
  hashes:
    binhash: 645606433a0831d31121f53848d95262
    md5: 12c7aa43b35110030002c7a81027cb20
work/access-om3.datm.r.1958-03-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.datm.r.1958-03-01-00000.nc
  hashes:
    binhash: 8b28b88535482decbae6497e312ae000
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-03-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.drof.r.1958-03-01-00000.nc
  hashes:
    binhash: 03af0f78189fdcb8b4208845eaecd934
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-03-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.mom6.r.1958-03-01-00000.nc
  hashes:
    binhash: bd8b15b5cf43d382e64280643a0df352
    md5: 3ee855b2cdcba628e85b0d7a821f23b7
work/access-om3.ww3.r.1958-03-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/access-om3.ww3.r.1958-03-01-00000
  hashes:
    binhash: 46924cad0187899e00f0e2d030713040
    md5: 789ea4292780dbb0b22a663ffd90a4f9
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.atm
  hashes:
    binhash: cf56e11e6fb035328b18136a91f570c6
    md5: c24ee337d34733cce5cad2f21e281d42
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.cpl
  hashes:
    binhash: 4b1e32a23e59f9e837925b15c1c863e0
    md5: 5ff2e8426c6fef71651984753d7b4222
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.ice
  hashes:
    binhash: 6c47aaf65c62feb068244e6c851b6624
    md5: a81ada9cdbd6580fd105bc62f7b67f1a
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.ocn
  hashes:
    binhash: 48ea21b2731938be0ebdc84a0a3c43c2
    md5: e3e436d7e415654dbfece12839cf57c1
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.rof
  hashes:
    binhash: b543d6ccddb4fdeb166060c5a69cc050
    md5: 0e7759e7dc5c6f0e62ff405e701d5343
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart001/rpointer.wav
  hashes:
    binhash: eea9214de30f64e681943194514fb10a
    md5: bf82b8f63555d913d7d6e27c3b4b6750
