format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-04-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.cice.r.1958-04-01-00000.nc
  hashes:
    binhash: adc1985be4b1706d579008a7604fda73
    md5: 642d93d497f020e48beb1e4a7c63214d
work/access-om3.cpl.r.1958-04-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.cpl.r.1958-04-01-00000.nc
  hashes:
    binhash: cf3897215a9bd53cb4d8a609763091dc
    md5: ffc926a9f3cd6abaed29394433b0809c
work/access-om3.datm.r.1958-04-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.datm.r.1958-04-01-00000.nc
  hashes:
    binhash: 41b5da2a0e1bf262141f0d57f7afe710
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-04-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.drof.r.1958-04-01-00000.nc
  hashes:
    binhash: 9faf8eac92a0ff200bf47a1f239239f5
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-04-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.mom6.r.1958-04-01-00000.nc
  hashes:
    binhash: 53e6b8e6b217a96df6781240c118f954
    md5: 15b75212f7d7921e1f18f7aa69ab3031
work/access-om3.ww3.r.1958-04-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/access-om3.ww3.r.1958-04-01-00000
  hashes:
    binhash: 72cda7ab42a4a2183ac93dc161030e4a
    md5: 1165896cbfe70d6f9a5d8d6f155e721d
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.atm
  hashes:
    binhash: 365722b33a81c68af822e3aff5736c02
    md5: 084ddc7829b55dc2a5f1ea13c4998d91
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.cpl
  hashes:
    binhash: fd45f0ac6ed9db5fc81279283d82ef36
    md5: 3fdb1e5dd788de889a84fa37fef9565f
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.ice
  hashes:
    binhash: 8a6f1b424d281ad89130c8f9f1fda270
    md5: f119e37b6e06bf6e60c067f1ba3a32ec
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.ocn
  hashes:
    binhash: f166b7e5b172de16faa36c0c9dbd4e79
    md5: 1d9e09b22ce7c3cfb1b94569eddc0f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.rof
  hashes:
    binhash: d9972e6ab7e5d049d2d539ed6a6337ef
    md5: 2e11215bb50520bd66c9efd2d8e05004
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart002/rpointer.wav
  hashes:
    binhash: f627fb3db896470e2bdbd489290c38f0
    md5: adace2656e2d9b4a60d3f905f4998c43
