format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1902-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.cice.r.1902-12-01-00000.nc
  hashes:
    binhash: 76b02eac3d9369a924d80d8f15c6801f
    md5: ed68fefad786dc9defa393dba677102f
work/access-om3.cpl.r.1902-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.cpl.r.1902-12-01-00000.nc
  hashes:
    binhash: bb764a8dda0a923f7675cde1300b4fad
    md5: 870f8642022a1163bc29984dba39d834
work/access-om3.datm.r.1902-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.datm.r.1902-12-01-00000.nc
  hashes:
    binhash: f8b06edf2a56faf65f9575d4a53f69e4
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1902-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.drof.r.1902-12-01-00000.nc
  hashes:
    binhash: 5a9f3d01e5818f188056d441482b4c3a
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1902-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.mom6.r.1902-12-01-00000.nc
  hashes:
    binhash: cded8b795c848ac41f54602bb9426eb6
    md5: d9ea45ccb285d02a1f854c5a0523dfba
work/access-om3.ww3.r.1902-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/access-om3.ww3.r.1902-12-01-00000
  hashes:
    binhash: a9de7cf9c06ccc72f7cffaac0b31ad0a
    md5: 18b8aa97f942fd7e8d53e3c46633a797
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.atm
  hashes:
    binhash: 7d95f77f60760bbd82f7e4f9f2abbec5
    md5: 68e876dab1a6e93a71f676348be46344
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.cpl
  hashes:
    binhash: faafe83529c7fb2b10856320ca8caf16
    md5: 359f2b5bd46dac78d4cca4a0b89c680a
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.ice
  hashes:
    binhash: fd544d8147c1940f6ff339e0f67cbd18
    md5: 932f7afcbdbe2a6915d3a028ea877ff6
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.ocn
  hashes:
    binhash: bca50abb625af21728dbaa65cc4a6e56
    md5: 3b7ea7452d3bb4d2e6634741173a9556
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.rof
  hashes:
    binhash: 229f32004814e443dddd1ef20f6d51c1
    md5: e15c23247111c7567f0300c6077c054e
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart034/rpointer.wav
  hashes:
    binhash: 3e08fbade7f557e087bca0a0728cb8b9
    md5: 422a0b304d7e90375bbaa9df0f97a021
