format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.cice.r.1958-05-01-00000.nc
  hashes:
    binhash: 277a4252ed4633b87c51d714660d191b
    md5: f59505f1b58397b7526b715360bcc287
work/access-om3.cpl.r.1958-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.cpl.r.1958-05-01-00000.nc
  hashes:
    binhash: 88609a1c851422d328d90059f29c4293
    md5: 7aeca7cfd2282576b8da972259a65e71
work/access-om3.datm.r.1958-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.datm.r.1958-05-01-00000.nc
  hashes:
    binhash: 87214c26fa6b1fc271804ddbd3ad034e
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.drof.r.1958-05-01-00000.nc
  hashes:
    binhash: a53c12d35dfd62c748d3cccc5b748725
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.mom6.r.1958-05-01-00000.nc
  hashes:
    binhash: d0b6dfd367eb45e8c6c3af46a7cce63c
    md5: 09ca1adc1def8b6bc378a7bbb1fd3448
work/access-om3.ww3.r.1958-05-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/access-om3.ww3.r.1958-05-01-00000
  hashes:
    binhash: ff4b53f9aa390c4ab693ec0f4959edee
    md5: fec5c988c6bd6d56f18317d4be166b5e
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.atm
  hashes:
    binhash: 5b24ac19c361eaba0ab5966e13a143b0
    md5: 322639226cc0693487f351edda5f5293
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.cpl
  hashes:
    binhash: c78a58ab9e94c13f378a8c2afafdb85d
    md5: e313475411e61aca840490118505a1a5
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.ice
  hashes:
    binhash: 25237007c04c37e4673a45b560f75f06
    md5: 70577d3e599f075502ac955e691422c0
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.ocn
  hashes:
    binhash: 63dc03fb7a8b9e1171f1ae785d7f32c6
    md5: 584837c820e504c3f76c4af782f2f5c9
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.rof
  hashes:
    binhash: 7b87aab4c5f1eba509a95651a54de1cb
    md5: b9e568604f72fb658c804fbf765b6d5f
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart003/rpointer.wav
  hashes:
    binhash: 3586d57ff903ebca6dabcee4837390da
    md5: 95f904d7e52c1cf131f314ac4d6a5471
