format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.cice.r.1900-02-01-00000.nc
  hashes:
    binhash: fd9b7f7bcdb1885292fdb3dd7ba0ef69
    md5: 5a9d4da7c0a1d9c3392d1480ada04b4e
work/access-om3.cpl.r.1900-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.cpl.r.1900-02-01-00000.nc
  hashes:
    binhash: 6d7ef8f4841bfa458cce535a1a57040a
    md5: fc6464b2b563d51130e243c05b9fe59e
work/access-om3.datm.r.1900-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.datm.r.1900-02-01-00000.nc
  hashes:
    binhash: be5b02aded26a65dec7f02e1202b93a4
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.drof.r.1900-02-01-00000.nc
  hashes:
    binhash: 3ec250d37e9dce02458b86d2e6e98688
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.mom6.r.1900-02-01-00000.nc
  hashes:
    binhash: 3565b5a923ff7b0030f71f7b7bbc7f57
    md5: a625c3111b83145e09d03135cc0a4c71
work/access-om3.ww3.r.1900-02-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/access-om3.ww3.r.1900-02-01-00000
  hashes:
    binhash: 6de380438c8d29b4ec907afc3ab9301e
    md5: b22318507d6b9a0cb08d92e9c7a4ef48
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.atm
  hashes:
    binhash: 670aa136ddbf3c9a4810e30da33ea9e7
    md5: bd9e55d4c79406b2b0d0b49972b19138
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.cpl
  hashes:
    binhash: 22e3e19d985641b58647c3f2beecee2a
    md5: f78aca9a14d6fdea61e3325944957e72
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.ice
  hashes:
    binhash: f25f4d6f0e2d3283d90926278817cb72
    md5: 959e57bc31b34017a11eb8ff594844e6
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.ocn
  hashes:
    binhash: d416557a031111b67bd6086acc0ba1ee
    md5: 8ef42be53c0bac69c95875f890fa7f4e
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.rof
  hashes:
    binhash: 829f2c7a52cb6b4b3b1ec1d5dffc4a22
    md5: 7a832b03e631c040a77aa0458e041ab1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC3-MCW-100km_jra_ryf/restart000/rpointer.wav
  hashes:
    binhash: 3595cf581f2b4218707f496801d8c6a8
    md5: 2cf7565e95536495bc86f513926bdcc1
