format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.cice.r.1900-12-01-00000.nc
  hashes:
    binhash: ecb0aeda6eb4fd20a95d78a2ce08cebb
    md5: e8336af64cd09c43f4a85acf6a336379
work/access-om3.cpl.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.cpl.r.1900-12-01-00000.nc
  hashes:
    binhash: 22c48c524ee520ad661253ed1b8ca755
    md5: dc12f8727d603fbbe4beb1c3e9ca4068
work/access-om3.datm.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.datm.r.1900-12-01-00000.nc
  hashes:
    binhash: 3af5eaf7dd66044ee45cf74b1b5ce693
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.drof.r.1900-12-01-00000.nc
  hashes:
    binhash: 6484fb5c86ebed7b5b54b433c4545fd4
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.mom6.r.1900-12-01-00000.nc
  hashes:
    binhash: e86b9f5c1e601e546f54c2781f8d3594
    md5: d6854365feecb7442f2d3b037d942e00
work/access-om3.ww3.r.1900-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/access-om3.ww3.r.1900-12-01-00000
  hashes:
    binhash: d0135233722b5cfbe3a7b737f91dda36
    md5: 1612ddfd1e0f487e37ac70ba5831b565
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.atm
  hashes:
    binhash: 2f01c1e76c8d414209af6a2e0b87d725
    md5: 6541a3071b60c0b24a14b1e5e87c12bd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.cpl
  hashes:
    binhash: 2768b412ef3fedae5357de7a76de4dc3
    md5: 014c83876045314eafa8ad92bf7c5947
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.ice
  hashes:
    binhash: 6a6f31d21405d0ab8cdb2e0249d6345d
    md5: 3e431a349c0689e87ddeba208fbb4427
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.ocn
  hashes:
    binhash: b155b8e736ce4a6090e802deee0f9e16
    md5: 2800ac83e9a9360b1cb9dd4a68245f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.rof
  hashes:
    binhash: d1ee29bf968a91b5667c727da9357d71
    md5: f782c8d6699ffeecc6ff7b5bb71543d1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf/restart010/rpointer.wav
  hashes:
    binhash: 0a48c223e623d8f1a611e55168f8cd8c
    md5: 4113cd2eb4dd550297ef51dc381b0e35
