format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-08-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.cice.r.1958-08-01-00000.nc
  hashes:
    binhash: a2900db86576d033b42254fc01842a83
    md5: f3ff7f4768897bb13abb80d5afb3e35e
work/access-om3.cpl.r.1958-08-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.cpl.r.1958-08-01-00000.nc
  hashes:
    binhash: d158c40ad7fe705aa6ca7202a6d1a91c
    md5: 4e807b4e8b7522fc2eca1057bc36a7fb
work/access-om3.datm.r.1958-08-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.datm.r.1958-08-01-00000.nc
  hashes:
    binhash: 4410ca336b455aa868ff6a903f4567da
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-08-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.drof.r.1958-08-01-00000.nc
  hashes:
    binhash: 73c72e18ff782c483f992b57156097f9
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-08-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.mom6.r.1958-08-01-00000.nc
  hashes:
    binhash: 23f558215be3dd704c02cf4e69097ff7
    md5: 78d3b2559035648035f1740aecb0e9e1
work/access-om3.ww3.r.1958-08-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/access-om3.ww3.r.1958-08-01-00000
  hashes:
    binhash: ea7f8745d19a17a6f904e34a85fe4f66
    md5: 8b090325323770bc9fb9c6f41647b329
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.atm
  hashes:
    binhash: 98fb71f85d0b80f2dcb6e2d652232ede
    md5: 9f22322207931fd8ba97e01faa8a8c1a
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.cpl
  hashes:
    binhash: 614a65b42bbe942791cb7c50681aef53
    md5: b9f11fb232a646f97ceb00f533b7c16b
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.ice
  hashes:
    binhash: b1deaa248f355fd5d0fb2cc39e46627c
    md5: 233a4c589beff779643d818deb0c7580
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.ocn
  hashes:
    binhash: de39d40df16a441a1d4cff9316b254be
    md5: 108a8071f3e57d3eac606b456ed5860b
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.rof
  hashes:
    binhash: ffa7f55cd36219d0284d6dbb82da6c8e
    md5: af7b95ab596db1b9a619994e4c3b08f9
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart006/rpointer.wav
  hashes:
    binhash: 19148a9d86d6a0f776f6970baabbb5ce
    md5: d2633acbcb4633161c4d3a1a1f4d3ebf
