format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.cice.r.1900-12-01-00000.nc
  hashes:
    binhash: 4ebecae0e1a46570f014772ecd46a5ca
    md5: 8e34e046dacd09eaa2778282431cdd09
work/access-om3.cpl.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.cpl.r.1900-12-01-00000.nc
  hashes:
    binhash: f71f61d95a357d49e67a72c4e4ba14a2
    md5: b5f3779779f30e054936676d2eaef31a
work/access-om3.datm.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.datm.r.1900-12-01-00000.nc
  hashes:
    binhash: 467c829cca24909f3efc940dc6660ba7
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.drof.r.1900-12-01-00000.nc
  hashes:
    binhash: 1fdf13c3848859ec3b754cc617951dbc
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.mom6.r.1900-12-01-00000.nc
  hashes:
    binhash: f472271e76c9780e3ab8c1116b6a15ec
    md5: 257af60f9ac5d52ccce6cb6d2d356912
work/access-om3.ww3.r.1900-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/access-om3.ww3.r.1900-12-01-00000
  hashes:
    binhash: ba980d63faa6346963178474c4b23e1e
    md5: 2802cbf7447c8476dee708af93218a48
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.atm
  hashes:
    binhash: 93bc8c9350c9ea0e876eaca497b127cc
    md5: 6541a3071b60c0b24a14b1e5e87c12bd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.cpl
  hashes:
    binhash: eb3142e44c9083ff5fe2c9db47dbd3b9
    md5: 014c83876045314eafa8ad92bf7c5947
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.ice
  hashes:
    binhash: 07423fc2be1717a258aa285c4f591f85
    md5: 3e431a349c0689e87ddeba208fbb4427
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.ocn
  hashes:
    binhash: 6168f7127ee840d79daaf50cb344f0f4
    md5: 2800ac83e9a9360b1cb9dd4a68245f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.rof
  hashes:
    binhash: c181494fad28adf174c7a417b39dd49a
    md5: f782c8d6699ffeecc6ff7b5bb71543d1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart010/rpointer.wav
  hashes:
    binhash: b04ff232c78a9edb14f27df53583db45
    md5: 4113cd2eb4dd550297ef51dc381b0e35
