format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-06-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.cice.r.1958-06-01-00000.nc
  hashes:
    binhash: ed1bc7183a6c10f8e08b6c6f949e5b2f
    md5: 2e68481634c58ccdf246d48f075c8fc9
work/access-om3.cpl.r.1958-06-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.cpl.r.1958-06-01-00000.nc
  hashes:
    binhash: 7d6dccc1fdb07e11800d92157695b776
    md5: 46c6319ac6a4eca8e148402cb53a9086
work/access-om3.datm.r.1958-06-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.datm.r.1958-06-01-00000.nc
  hashes:
    binhash: 8730ebfd8531b2d0deda1eaa95ca5a65
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-06-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.drof.r.1958-06-01-00000.nc
  hashes:
    binhash: ff82e9541fd7d87d91c46cbaae5bfa9b
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-06-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.mom6.r.1958-06-01-00000.nc
  hashes:
    binhash: 3f4cda3459225bfc5bfa6560c9587b62
    md5: de64a9f7df00b51f991c0f347d4a102c
work/access-om3.ww3.r.1958-06-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/access-om3.ww3.r.1958-06-01-00000
  hashes:
    binhash: 391c9884c8c2db449e172bb1eae716a3
    md5: 17a3f616292f25f22de5b13664381ed9
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.atm
  hashes:
    binhash: 8537a17d2f2217f0310031aa33868fd7
    md5: 509d3c019eedab74c09db7de71db84fd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.cpl
  hashes:
    binhash: e42ce49113deb5e86823c97ede01ec17
    md5: 4c0d0b14065576e6ee44d7f9868b6006
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.ice
  hashes:
    binhash: 948e08f6d9c947d687f8c90f6f456acb
    md5: 4b876fd939df3c22f1ed78e5514bf60a
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.ocn
  hashes:
    binhash: 53876217cb13747b220971d86d45272b
    md5: 47e73cb38606ce1d9dde6fee023390a6
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.rof
  hashes:
    binhash: ee6e2f362e18bc4ae4f53b8be0ef897b
    md5: 1490d105e690b4f34fb02eb57313d64b
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart004/rpointer.wav
  hashes:
    binhash: 48ebd3849bb51a6bf7d8a0d9c9f89a09
    md5: 986f3a7bf57440e6ac3855cef6fd03c8
