format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-07-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.cice.r.1958-07-01-00000.nc
  hashes:
    binhash: 62aebc5f8de3466430dec932898f39df
    md5: 3ddea7926e7d499884d0fff24e9ae838
work/access-om3.cpl.r.1958-07-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.cpl.r.1958-07-01-00000.nc
  hashes:
    binhash: 8410c2681963dc4d080bf5c9fffd4d19
    md5: 8d9e1ca4ea9e23c14c0de4f0ae607f0b
work/access-om3.datm.r.1958-07-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.datm.r.1958-07-01-00000.nc
  hashes:
    binhash: d0e9f038ff80734a3e445b3e111213c2
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-07-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.drof.r.1958-07-01-00000.nc
  hashes:
    binhash: 6d3c0b778daf37e565a9c2af719ec0c6
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-07-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.mom6.r.1958-07-01-00000.nc
  hashes:
    binhash: 3ca90903e7ec800a2e0cae4267ca6735
    md5: bf147e8c21ea22294c9608dea1b3c6c6
work/access-om3.ww3.r.1958-07-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/access-om3.ww3.r.1958-07-01-00000
  hashes:
    binhash: a3fec0a943803b01508594e9ac81cc5f
    md5: 0066b45c95b77eb83f14e37d1c626e69
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.atm
  hashes:
    binhash: bf25395c0e826f63689c23bfccb9dfb5
    md5: f7284f5c91d8382bc084d2305b4b3054
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.cpl
  hashes:
    binhash: 270c00c0a2f0985fc9835aafca37b1d8
    md5: af93b0e010c275bcbeb5c8295dac7ad5
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.ice
  hashes:
    binhash: a0038faa2988b5d84082270f04b8256e
    md5: d3722285274deb15cc7e26b46723fefb
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.ocn
  hashes:
    binhash: e7f9e587f282ec2d8f6a4f51f317e445
    md5: 75a0787804aec6876fe5742cfea4fdb0
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.rof
  hashes:
    binhash: b83f4b45655083cafc4359f459fde9da
    md5: 280810d6d33fe600ac0a0855de44ec7d
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart005/rpointer.wav
  hashes:
    binhash: 42a729adc93aad3ba2a1cc87e1cbc86c
    md5: c2c75c1e0812c9844800b1b9c1ed3480
