format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.cice.r.1900-12-01-00000.nc
  hashes:
    binhash: c4748f35af746ce885d3aa8d940975e0
    md5: 4c3cef97256ebdc4d7e2f3035ccda85a
work/access-om3.cpl.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.cpl.r.1900-12-01-00000.nc
  hashes:
    binhash: 86d93759002587a45c0836ecd3a531e3
    md5: bff597c14a93493a5393d36d18ddd204
work/access-om3.datm.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.datm.r.1900-12-01-00000.nc
  hashes:
    binhash: babf985c0284b5503d1e15eb905a0ec0
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.drof.r.1900-12-01-00000.nc
  hashes:
    binhash: 008fce01f1723ce33c10f526bb04fe13
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.mom6.r.1900-12-01-00000.nc
  hashes:
    binhash: 9e306508a1072a3519b548fa81d134f3
    md5: 3be80831d13fd27c0232d5241e44fa0d
work/access-om3.ww3.r.1900-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/access-om3.ww3.r.1900-12-01-00000
  hashes:
    binhash: 7573b51f538e2d32d743735cc6d01c4b
    md5: 194580e1d7967214298f67de56765ff0
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.atm
  hashes:
    binhash: c2a03fa522f012f3ac5bab05d21aa15a
    md5: 6541a3071b60c0b24a14b1e5e87c12bd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.cpl
  hashes:
    binhash: aa2146ac235c9a831310a06bbbb0a5c3
    md5: 014c83876045314eafa8ad92bf7c5947
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.ice
  hashes:
    binhash: 3a47639f1944dba8b1eb18d346db23c1
    md5: 3e431a349c0689e87ddeba208fbb4427
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.ocn
  hashes:
    binhash: 3c6c8c6bf528275762acba3469f1dd4b
    md5: 2800ac83e9a9360b1cb9dd4a68245f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.rof
  hashes:
    binhash: 56eb82f76f1c4ffbd41c6ad7d35830bf
    md5: f782c8d6699ffeecc6ff7b5bb71543d1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_defaultmixing/restart010/rpointer.wav
  hashes:
    binhash: 2547f70536a836caa287723e855aac4e
    md5: 4113cd2eb4dd550297ef51dc381b0e35
