format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1958-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.cice.r.1958-02-01-00000.nc
  hashes:
    binhash: c92314ff929428cef1fa627a2f5ee989
    md5: 035e93e25e64292d48e3018b504703e5
work/access-om3.cpl.r.1958-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.cpl.r.1958-02-01-00000.nc
  hashes:
    binhash: cb48a9ed2f7d8b52f54b7ba3a32cd6b6
    md5: 2f48cf4d0e15bb42b3a4c07d43809b90
work/access-om3.datm.r.1958-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.datm.r.1958-02-01-00000.nc
  hashes:
    binhash: e545cc9abbcb6e79d175237917f0220a
    md5: 68fc0ead4896f51f80667dca87327711
work/access-om3.drof.r.1958-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.drof.r.1958-02-01-00000.nc
  hashes:
    binhash: 84ed2f9edd37ec323fe8b15a856c4ff7
    md5: c113a9eedc25af15bf1522cab2ddf48d
work/access-om3.mom6.r.1958-02-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.mom6.r.1958-02-01-00000.nc
  hashes:
    binhash: 8c0c9f9f2970ddb8fe3d4e6231c492da
    md5: db59b1ed20cff79732b089c158ebe952
work/access-om3.ww3.r.1958-02-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/access-om3.ww3.r.1958-02-01-00000
  hashes:
    binhash: 9e232c9586b7c19afe2cec331f905c04
    md5: 510fbdcd81b1e5b3b8b6fada7bbdedab
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.atm
  hashes:
    binhash: 97477419c11e15bb5f0b458722f89357
    md5: c314e523fa5d1b1ecac199b55469690f
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.cpl
  hashes:
    binhash: 9d855638be3e5ebd0479bb6c81ae9d4e
    md5: d84f64f8f2ea021a57f8a57ee4c635ad
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.ice
  hashes:
    binhash: 74f083a40ec4e318f3c7eab8506ab137
    md5: 201025e7fb20850dd6cfe620ef7e401c
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.ocn
  hashes:
    binhash: 2787ea7fdf69dc9c1a0cbf56e6f2bc5e
    md5: 64d672a9bac20e058f44233680d1349a
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.rof
  hashes:
    binhash: 505dc372ab8e9a28105a1cafc6f421ed
    md5: f667f090dda6a134539bd977ee48b65b
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4-IC4M2-MCW_100km_jra_iaf/restart000/rpointer.wav
  hashes:
    binhash: e0c71f31173cf29e69d1be47ffedf9d0
    md5: 52f6ba61394eeee06d2e2c5b278a924b
