format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1901-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.cice.r.1901-05-01-00000.nc
  hashes:
    binhash: 59700b8f5cca881d60349288be8289f4
    md5: 71492f471ce8a7d21b2c827c7527c62d
work/access-om3.cpl.r.1901-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.cpl.r.1901-05-01-00000.nc
  hashes:
    binhash: ab60a7e57f675a37376509518db6134a
    md5: cedd1c00ac472f26c6e4020975fc27e2
work/access-om3.datm.r.1901-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.datm.r.1901-05-01-00000.nc
  hashes:
    binhash: afff558298944f5ce9e169ef9e3ff47e
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1901-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.drof.r.1901-05-01-00000.nc
  hashes:
    binhash: e1c4a6c4db8b23dd123a38659250f190
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1901-05-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.mom6.r.1901-05-01-00000.nc
  hashes:
    binhash: e965641b0f935fe2c059cebd7c591f49
    md5: ca74894cbb84f86e331df92dd0e3da1d
work/access-om3.ww3.r.1901-05-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/access-om3.ww3.r.1901-05-01-00000
  hashes:
    binhash: b52314e5b85852099f49a05b57f20b88
    md5: db543c297913b9670ea3869d9dd086cb
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.atm
  hashes:
    binhash: 90ddcbdf4c0958130d0237097cf4ec1e
    md5: eaf19945f6de5b853227b3184a40365a
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.cpl
  hashes:
    binhash: b89a5085178a511586d823246766ec48
    md5: 34400ad73b4c6142d5844e3040c9090f
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.ice
  hashes:
    binhash: e22469edce27643ac16d49d5cfb16bfd
    md5: d3df999b58ea3f9458692d2bf8713b60
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.ocn
  hashes:
    binhash: 29527771700b0773d7bc225ccf400fc5
    md5: 84f62c7a4e96f45330ecb55867d928e5
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.rof
  hashes:
    binhash: 8f7e57ed4efdafceb9404270b4758a21
    md5: 5154a8b3521bdb84337ee1d198e980cd
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M8-MCW-100km_jra_ryf_nomixing/restart015/rpointer.wav
  hashes:
    binhash: dff84ffa3d8f44ad1b06aae2e2136256
    md5: 8d4ea9bcd270edd5058d23adbd0b76ff
