format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.cice.r.1900-12-01-00000.nc
  hashes:
    binhash: 91b8f1abe5dd3f175305bb8f28c849f5
    md5: 276d56100b105db0d747de06e980021a
work/access-om3.cpl.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.cpl.r.1900-12-01-00000.nc
  hashes:
    binhash: 6ecc2ad7e22cc42cd8f533846c321248
    md5: 6698c9d5ba2b67cf1a4d34f246356747
work/access-om3.datm.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.datm.r.1900-12-01-00000.nc
  hashes:
    binhash: f2ebea040cf55757d120b92973a0d3ca
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.drof.r.1900-12-01-00000.nc
  hashes:
    binhash: 91f5b4af4709ff62f0416f79d08e4cf7
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.mom6.r.1900-12-01-00000.nc
  hashes:
    binhash: 970397c4fd13dfc88ecc549b84bab004
    md5: 01393e3a5c16140d3d24986f28a2d450
work/access-om3.ww3.r.1900-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/access-om3.ww3.r.1900-12-01-00000
  hashes:
    binhash: 938bea6634c5778ac9e1324ac189743c
    md5: bf2a8a1a8633eb3dc8b9ef2a2fb469c8
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.atm
  hashes:
    binhash: b899b9ec5909a6a50d49b9d76645867e
    md5: 6541a3071b60c0b24a14b1e5e87c12bd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.cpl
  hashes:
    binhash: faca92da17c944f7451ccf47d4a8e5b1
    md5: 014c83876045314eafa8ad92bf7c5947
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.ice
  hashes:
    binhash: 34d6b70b323264ceb0721be179909b8e
    md5: 3e431a349c0689e87ddeba208fbb4427
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.ocn
  hashes:
    binhash: 57ebe769b363fd15f9d39be825dc2ae3
    md5: 2800ac83e9a9360b1cb9dd4a68245f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.rof
  hashes:
    binhash: b68ccc608f2f0c1488921146c4177715
    md5: f782c8d6699ffeecc6ff7b5bb71543d1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M2-MCW-100km_jra_ryf/restart010/rpointer.wav
  hashes:
    binhash: 03aff5f304d6184a052d0b915b9d11da
    md5: 4113cd2eb4dd550297ef51dc381b0e35
