format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.cice.r.1900-12-01-00000.nc
  hashes:
    binhash: 39c47e8f615dcf7c293d70add80c5c21
    md5: 3db1e62c19fdec67b5b21afb54f66dce
work/access-om3.cpl.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.cpl.r.1900-12-01-00000.nc
  hashes:
    binhash: def5deddc28275e9bfcef481033b0f0d
    md5: b0ef85b21bdfadc59566e5aace6afb1a
work/access-om3.datm.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.datm.r.1900-12-01-00000.nc
  hashes:
    binhash: b79fc7d0ef7626e841c296e1a1024103
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.drof.r.1900-12-01-00000.nc
  hashes:
    binhash: 028e5e60dfcfe393d1439b45592b1aae
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1900-12-01-00000.nc:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.mom6.r.1900-12-01-00000.nc
  hashes:
    binhash: 6a0bd6154c998d1eabfb2fdde6c00e88
    md5: aba030242daa6fe905f4e5bba0106780
work/access-om3.ww3.r.1900-12-01-00000:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/access-om3.ww3.r.1900-12-01-00000
  hashes:
    binhash: 3644d4a0c5c589056fdd107043b8ccf7
    md5: 9c232d3fb217e5ec9249b3035b5cd48c
work/rpointer.atm:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.atm
  hashes:
    binhash: 4fbabc8146104b6671611648a2524b33
    md5: 6541a3071b60c0b24a14b1e5e87c12bd
work/rpointer.cpl:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.cpl
  hashes:
    binhash: e22ffd1b46568289ca38854d6df3db61
    md5: 014c83876045314eafa8ad92bf7c5947
work/rpointer.ice:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.ice
  hashes:
    binhash: a11bf5405bd8679f48dabef674f82bef
    md5: 3e431a349c0689e87ddeba208fbb4427
work/rpointer.ocn:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.ocn
  hashes:
    binhash: 622359732a2d6d606157b20f15a1c99e
    md5: 2800ac83e9a9360b1cb9dd4a68245f60
work/rpointer.rof:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.rof
  hashes:
    binhash: 5db5dbc1733f853a72779e9afdf6516a
    md5: f782c8d6699ffeecc6ff7b5bb71543d1
work/rpointer.wav:
  fullpath: /scratch/ps29/nd0349/access-om3/archive/IC4M3-MCW-100km_jra_ryf/restart010/rpointer.wav
  hashes:
    binhash: bd5049e2546926699c6aef8617bf98f2
    md5: 4113cd2eb4dd550297ef51dc381b0e35
